language: bash
matrix:
    include:
        - env: test=ssh-agent filter=true image=container-trusty
          sudo: false
          dist: trusty
          install: eval `ssh-agent -s`
        - env: filter=false image=container-trusty
          sudo: false
          dist: trusty
          filter_secrets: false
          install: eval `ssh-agent -s`
        - env: test=sleep filter=true image=container-trusty
          sudo: false
          dist: trusty
          install: "setsid sh -c 'sleep 1000' &"
        - env: test=sleep filter=false image=container-trusty
          sudo: false
          dist: trusty
          filter_secrets: false
          install: "setsid sh -c 'sleep 1000' &"
script:
    - sleep 1
    - declare -f travis_terminate
    - echo $$
    - ps -jef --forest 2>/dev/null || ps -jef
notifications:
    email: never
