language: minimal
matrix:
    include:
        - env: test=osx
          os: osx
          osx_image: xcode7.3
        - env: test=container
          dist: trusty
          sudo: false
        - env: test=sudo-nofilter
          dist: trusty
          sudo: required
script:
    - echo $c_space_d_quoted to stdout
    - echo $c_space_d_quoted to stderr >&2
    - ps -jef --forest
    - ls -lL /dev/fd
notifications:
    email: never
